#
#  *******************************************************************************
#  Copyright (c) 2025 Eclipse Foundation and others.
#  This program and the accompanying materials are made available
#  under the terms of the Eclipse Public License 2.0
#  which is available at http://www.eclipse.org/legal/epl-v20.html
#  SPDX-License-Identifier: EPL-2.0
#  *******************************************************************************
#
apiVersion: v2
name: otterdog
description: An otterdog Web App Helm chart for Kubernetes
home: https://github.com/eclipse-csi/otterdog
icon: https://raw.githubusercontent.com/eclipse-csi/.github/refs/heads/main/artwork/eclipse-otterdog/Logo%20Color%20-%20Transparent%20Bg.png
sources:
  - https://github.com/eclipse-csi/otterdog
  - https://github.com/eclipse-csi/helm-charts
keywords:
  - otterdog
  - github
  - configuration-as-code
  - eclipse
  - security
maintainers:
  - name: eclipse-csi
    url: https://github.com/eclipse-csi/otterdog/
type: application
kubeVersion: ">=1.23.0-0"
version: 1.2.1
appVersion: "1.4.0"
dependencies:
  - name: ghproxy
    version: 0.4.0
    # repository: "file://../ghproxy"
    repository: "https://eclipse-csi.github.io/helm-charts"
    condition: ghproxy.enabled
  - name: mongodb
    version: 0.18.1
    repository: "oci://registry-1.docker.io/cloudpirates"
    condition: mongodb.enabled
  - name: valkey
    version: 0.24.3
    repository: "oci://registry-1.docker.io/cloudpirates"
    condition: valkey.enabled
